[windows]
3.12.111.83

[windows:vars]
ansible_user=ansible
ansible_password=wm6*m3zE3sGN2
ansible_port=5986
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
